### ISSUE TITLE
Cinnamon is making my Qt apps look ugly by overriding QT_STYLE_OVERRIDE

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon-session#76] opened 2016-07-14 12:08 UTC
Just moving [this issue](https://github.com/linuxmint/Cinnamon/issues/5440) to the right place.

Qt [5.7](https://github.com/qt/qtbase/commit/899a815414e95da8d9429a4a4f4d7094e49cfc55) will change gtk style architecture.

New style override variable seems to be ["gtk2"](https://github.com/qt/qtstyleplugins/blob/master/src/plugins/styles/gtk2/gtk2.json)

Hardcoding env vars is always a bad idea. Drop [that](https://github.com/linuxmint/cinnamon-session/blob/96f25057cac202e13c338886d00bc0383394ad26/cinnamon-session/main.c#L387) line and set the env var in /etc/profile.d or /etc/environment or whereever, but not in C code. (Where a user/sysadmin can change it without recompiling cinnamon)

**Comment by ManuelSchneid3r** [comment] 2016-10-01 17:46
Almost three months for a single line. Has cinnamon been abandoned?

**Comment by clefebvre** [comment] 2016-10-01 21:43
Duplicate of https://github.com/linuxmint/Cinnamon/issues/5440

**Closed by clefebvre** 2016-10-01 21:43 UTC
